import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class DetailsPage extends StatefulWidget
{
  State<StatefulWidget> createState()
  {
    return DetailsPageState();
  }
}

class DetailsPageState extends State<DetailsPage>
{
  bool isFavourite = false;
  Widget build(BuildContext context)
  {
    Widget details;
    try{
    details = new Container(
        child: NestedScrollView(
            headerSliverBuilder: (BuildContext context,bool innerBoxisScrolled){
              return [
                SliverAppBar(
                  elevation: 50,
                  backgroundColor: Colors.indigo[600],
                  expandedHeight: 200.0,
                  floating: false,
                  actions: [
                    IconButton(
                      icon: isFavourite ? Icon(Icons.favorite,color: Colors.red):Icon(Icons.favorite_border),
                      onPressed: (){ 
                        if(isFavourite){
                          setState(() {
                          this.isFavourite = false;
                        });
                        }
                        else
                        setState(() {
                          this.isFavourite = true;
                     
                        });
                      },
                    )
                  ],
                  pinned: true,
                  flexibleSpace: FlexibleSpaceBar(
                    
                    centerTitle: true,
                    title: Text("Landing Page"),
                    collapseMode: CollapseMode.parallax,
                    background: Image.asset("assets/web.jpg",fit: BoxFit.fitWidth), 
                  ),
                ),
              ];
            },
            body: new Container(
            decoration: BoxDecoration(borderRadius: BorderRadius.only(topLeft: Radius.circular(25),topRight: Radius.circular(25))),  
            child: 
            SingleChildScrollView(
              padding: EdgeInsets.all(15),
              child:
              Column(children: [
              Text("Landing Page"),
              Text("""In online marketing, a landing page, sometimes known as a \"lead capture page\", \"static page\", or a \"destination page\", is a single web page that appears in response to clicking on a search engine optimized search result,marketing promotion, marketing email, or an online advertisement. The landing page will usually display directed sales copy that is a logical extension of the advertisement, search result or link. Landing pages are used for lead generation. The actions that a visitor takes on a landing page is what determines an advertiser\'s conversion rate.Landing pages are often linked to social media, e-mail campaigns or search engine marketing campaigns in order to enhance the effectiveness of the advertisements. 
            The general goal of a landing page is to convert site visitors into sales or leads. If the goal is to obtain a lead, the landing page will include some method for the visitor to get into contact with the company, usually a phone number, or an inquiry form. If a sale is required, the landing page will usually have a link for the visitor to click, which will then send them to a shopping cart or a checkout area. 
            By analyzing activity generated by the linked URL, marketers can use click-through rates and conversion rate to determine the success of an advertisement.""",style: TextStyle(wordSpacing: 2),)
              ]
              ),
          ),
          )
      ),
    );
    }catch(e){
      details = new Center(
        child: new CircularProgressIndicator(),
      );
      print(e.toString());
    }
    return Scaffold(
      body: details
    );
  }

}